spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:52000/remember
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: migu1234!
    hikari:
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
        hbm2ddl:
          auto: update # validate 나 none으로 변경

  thymeleaf:
    cache: 'false'
  logging:
    level:
      root: INFO
      org.springframework.web: INFO
