spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
  thymeleaf:
    cache: 'false'


